# @name CreateUserRole
POST http://localhost:9991/user-role
accept: application/json
content-type: application/json

{
  "Role": "supervip5"
}

### END

# @name GetUserRole
GET http://localhost:9991/user-role/27
accept: application/json
content-type: application/json

### END

# @name DeleteUserRole
DELETE http://localhost:9991/user-role/27
accept: application/json
content-type: application/json

### END

